service: serverless-plugin-ignitor-example

custom: 
  ignitor:
    hello:
      wrapper: wrappers.logger
      schedule:
        rate: rate(5 minutes)
        enabled: true
        input: 
          source: 'logger'

    /good.*/:
      schedule: false

    /non-matching/:
      schedule: true
      
  webpack:
    includeModules: false
    packager: 'yarn'

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2 
  package:
    individually: true

functions:
  hello:
    handler: handlers.hello
    timeout: 10
  goodbye:
    handler: handlers.goodbye

plugins:
  - serverless-plugin-ignitor
  - serverless-webpack