service: serverless-plugin-ignitor-example

custom: 
  ignitor:
    functions:
      - hello
  webpack:
    includeModules: false
    packager: 'yarn'

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2 
  package:
    individually: true

functions:
  hello:
    handler: handlers.hello
    timeout: 10
  goodbye:
    handler: handlers.goodbye

plugins:
  - serverless-plugin-ignitor
  - serverless-webpack